name: Health check invoke via cron 

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 12 * * *'
    - cron:  '30 01 * * *'
jobs:
  call-workflow-passing-data:
    if: github.event.schedule == '30 12 * * *'
    uses: ./.github/workflows/healthcheck.yml
    with:
      env: QA
    secrets: inherit
    
  call-workflow-passing-data1:
    if: github.event.schedule == '30 01 * * *'
    uses: ./.github/workflows/healthcheck.yml
    with:
      env: SIT
    secrets: inherit
